
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
     # We don't want the branch on master because it causes merge conflits when we merge another branch into it
    target-branch: "2022-Q1-features"
    labels:
      - "Dependencies"
